config/routes.rb
# frozen_string_literal: true

Rails.application.routes.default_url_options = {
    host: ENV['APPLICATION_BASE_URL']
}

Rails.application.routes.draw do
  resources :config_variables
  

  resources :picks
  mount ActionCable.server => '/cable'

  devise_for :supports
  scope module: :support do
    get '/', to: 'home#index', as: :support_root
    authenticated :support do
      get '/search/users', to: 'search#users', as: :support_user_search
      get '/search/designers', to: 'search#designers', as: :support_designer_search
      get '/search/orders', to: 'search#orders', as: :support_order_search
      get '/search/requests', to: 'search#requests', as: :support_request_search
      get 'search/user-suggestions', to: 'search#users_suggestions'
      get 'search/designer-suggestions', to: 'search#designers_suggestions'
      
      # Generating Reports Based on the Queries 
      get 'supports/reports' => 'reports#list_reports', as: :support_reports 
      get 'supports/requests_24' => 'reports#requests_24'
      get 'supports/requests_48' => 'reports#requests_48'
      get 'supports/no_offer_custumise_24' => 'reports#no_offer_custumise_24'
      get 'supports/no_offer_custumise_48' => 'reports#no_offer_custumise_48'
      get 'supports/awating_meas' => 'reports#awating_meas'
      get 'supports/no_offer_requests_24' => 'reports#no_offer_requests_24'
      get 'supports/no_offer_requests_48' => 'reports#no_offer_requests_48'
      get 'supports/user_nooffer_24' => 'reports#user_nooffer_24'
      get 'supports/user_nooffer_48' => 'reports#user_nooffer_48'
      get 'supports/hot_users' => 'reports#hot_users'
      get 'supports/warm_users' => 'reports#warm_users'
      get 'supports/cold_users' => 'reports#cold_users'
      get 'supports/offer_requests' => 'reports#offer_requests'
      get 'supports/requests_nooffers_10000' => 'reports#requests_nooffers_10000'
      get 'supports/requests_nooffers_10_15' => 'reports#requests_nooffers_10_15'
      get 'supports/requests_nooffers_15000' => 'reports#requests_nooffers_15000'

      

      resources :users, only: %i[index show update], as: :support_users
      resources :designers, only: %i[index show], as: :support_designers
      resources :requests, only: %i[index show update create], as: :support_requests do
        patch :approve
        patch :reject
      end
      get '/send_messages' => 'messages#index'
      post '/send_messages' => 'messages#create'
      post 'supports/conversations' => 'users#create', as: :support_conversation
      resources :orders, only: %i[index], as: :support_orders  
      resources :orders, only: %i[show], as: :support_show_orders  
      resources :offers, only: %i[index show destroy], as: :support_offers  
      post 'offer_quotation/:offer_id' => 'offers#create_quotation', as: :support_offer_quotation
      patch 'offer_quotation/:offer_id' => 'offers#update_quotation', as: :support_offer_update 

      resources :chats, only: %[index], as: :support_chats
    end
  end

  scope module: :v1, path: 'supports', constraints: RouteConstraints.new(version: 1, default: true),
  defaults: { format: :json } do
    scope module: :supports do
      post 'login', to: 'sessions#create'
      post 'update_devise_token', to: 'registrations#update_devise_token'
      #notifications
      post 'notifications', to: 'messages#notifications'

      resources :conversations, only: %i[index create show destroy] do
        collection do
          post :chat_type
          post :fetch_conversation
          get :init_data
        end
        member do
          resources :messages, only: %i[index create update]
        end
      end
    end
  end

  get '/quoation/:id' => 'support/requests#show_request_quo', as: :quoation
  get '/product/:id' => 'support/designers#show_product_details', as: :product  

  get '/chat/:id' => 'support/requests#chat', as: :chat
  post '/chat/:id' => 'support/requests#chat_post', as: :chat_post
  post '/request_images' => 'support/requests#request_images'

  post '/gallery_images' => 'support/offers#gallery_images'

  get '/designers/measurements' => 'v1/designers/offer_quotations#measurement_tags'

  get '/push_token' => 'support/push_tokens#index'
  post '/push_token' => 'support/push_tokens#create', as: :push_create

  get '/users/create_request/:id' => 'support/users#create_request', as: :support_create_request  

  resources :measurement_tags
  
  resources :events, only: %i[index create]


  # constraints(subdomain: 'support') do
  #   devise_for :supports, path: ''
  #   scope module: :support do
  #     get '/', to: 'home#index', as: :support_root
  #     authenticated :support do
  #       get '/search/users', to: 'search#users', as: :support_user_search
  #       get '/search/designers', to: 'search#designers', as: :support_designer_search
  #       get '/search/orders', to: 'search#orders', as: :support_order_search
  #       get 'search/user-suggestions', to: 'search#users_suggestions'
  #       get 'search/designer-suggestions', to: 'search#designers_suggestions'
  #       resources :users, only: %i[index show], as: :support_users
  #       resources :designers, only: %i[index show], as: :support_designers
  #       resources :requests, only: %i[index show], as: :support_requests do
  #         patch :approve
  #         patch :reject
  #       end
  #       resources :orders, only: %i[index show], as: :support_orders
  #     end
  #   end
  # end

  root 'home#index'

  scope module: :v1, path: 'users', constraints: RouteConstraints.new(version: 1, default: true),
    defaults: { format: :json } do
    scope module: :users do
      # Registration
      post 'sign-up', to: 'registrations#create'
      get 'confirm/:token', to: 'registrations#confirm'
      post 'resend-confirmation-email', to: 'registrations#resend_confirmation'
      post 'send-reset-password-instructions', to: 'registrations#send_reset_password_instructions'
      get 'reset-password/:token', to: 'registrations#reset_password'
      get 'people', to: 'registrations#people'
      post 'update-password', to: 'registrations#update_password'
      post 'update-mobile-number', to: 'registrations#update_mobile_number'
      post 'update_devise_token', to: 'registrations#update_devise_token'
      post 'update_membership', to: 'registrations#update_membership'
      get 'resend-otp', to: 'registrations#resend_otp'
      post 'verify-otp', to: 'registrations#verify_otp'
      get 'me', to: 'registrations#show'
      post 'me/update', to: 'registrations#update'
      delete '/me/delete', to: 'registrations#destroy'

      #notifications
      post 'notifications', to: 'messages#notifications'
      # Authentication
      post 'login', to: 'sessions#create'
      match 'auth/facebook', to: 'sessions#facebook', via: %i[get post]
      match 'auth/google', to: 'sessions#google', via: %i[get post]

      # Home Controller
      get 'home/mobile', to: 'home#mobile'
      get 'home/mobile_v2', to: 'home#mobile_v2'

      # Sub Categories
      resources :sub_categories, only: :index, path: 'sub-categories'

      # Designers
      resources :designers, only: %i[index show]

      # Requests
      resources :requests, only: %i[index create show] do
        collection do
          get :init_data, path: 'init-data'
          get 'designers/:category_id' => :designers
          post  :create_v2
          post  :create_request_images_v2
        end
        member do
          resources :offers, only: %i[index show]
        end
      end

      # Offers
      resources :offers, only: %i[index show]

      # Shipping Addresses
      resources :addresses, only: %i[index create]

      resources :products, only: %i[index show]

      get 'explore/mobile', to: 'explore#mobile'
      get 'explore/mobile_v2', to: 'explore#mobile_v2'
      get 'search/:q', to: 'search#index'
      post 'external-search/create', to: 'external_searches#create'
      get 'external-search/modal-suggestions', to: 'external_searches#search_suggestions'
      get 'external-search/top-suggestions', to: 'external_searches#top_query_suggestions'

      resources :orders, only: %i[index show create] do
        member do
          get :pay
          get :measurement_tags
          post :update_measurements
          post :update_measurements_v2
          post :submit_options
          get :cancel_order
        end
      end

      resources :order_payments, only: %i[create update]

      # resources :support_chats, only: %i[create index] do
      #   member do
      #     resources :conversations, only: %i[create]
      #   end
      # end

      resources :conversations, only: %i[index create show destroy] do
        collection do
          get :chat_type
          post :fetch_conversation
          #get :chat_type_request
        end
        member do
          resources :messages, only: %i[index create update]
        end
      end

      resources :offer_quotation_chats, only: %i[create] do
        member do
          resources :conversations, only: %i[create]
        end
      end

      resources :user_favorite_products, only: :create, path: 'add-to-wishlist'
      resources :user_favorite_designers, only: :create, path: 'add-to-favorites'
    end
  end

  scope module: :v1, path: 'designers', constraints: RouteConstraints.new(version: 1, default: true),
    defaults: { format: :json } do
    scope module: :designers do
      # Registration
      post 'sign-up', to: 'registrations#create'
      get 'confirm/:token', to: 'registrations#confirm'
      post 'resend-confirmation-email', to: 'registrations#resend_confirmation'
      post 'send-reset-password-instructions', to: 'registrations#send_reset_password_instructions'
      get 'reset-password/:token', to: 'registrations#reset_password', :constraints => { :token => /.+@.+\..*/ }
      post 'update-password', to: 'registrations#update_password'
      post 'update-mobile-number', to: 'registrations#update_mobile_number'

app/controllers/support/chats_controller.rb
class Support::ChatsController < ApplicationController
  
  def index
    convo_id = Message.pluck(:conversation_id).uniq
    user_id = Conversation.where(id:convo_id).pluck(:conversationable_id)
    @users = User.where(id:user_id).order(updated_at: :desc).paginate(:page => params[:page], :per_page => 100)
  end

end

app/controllers/support/designers_controller.rb
# frozen_string_literal: true

class Support::DesignersController < ApplicationController
  def index
    @designers = Designer.order(full_name: :asc).all
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "Designer" )
    @conversation = Conversation.new
  end

  def show
    @designer = Designer.find(params[:id])
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "Designer", conversationable_id:@designer).first 
  end

  def show_product_details
  	@product = Product.find(params[:id])
  end
end

app/controllers/support/home_controller.rb
# frozen_string_literal: true

class Support::HomeController < ApplicationController
  def index
    if support_signed_in?
      @data = {
        total_users:     User.count,
        total_designers: Designer.count,
        total_requests:  Request.count,
        total_offers:    OfferQuotation.count,
        total_orders:    Order.count,
        total_products:  Product.count
      }
    else
      redirect_to '/supports/sign_in'
    end
  end
end

app/controllers/support/messages_controller.rb
# frozen_string_literal: true
class Support::MessagesController < ApplicationController
    
  def index
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save!(validate:false)
      if params[:commit] == "CLOSE REQUEST"
        @notification.delay.close_request_message(@notification) 
      elsif params[:commit] == "SUBMIT REQUEST"
        @notification.delay.submit_request_message(@notification)
      elsif params[:commit] == "ALL USERS"    
        @notification.delay.all_users_message
      end
      flash[:success] == "Message Sent"
      redirect_to send_messages_path
    else
      redirect_to root_url
    end  
  end

  private

  def notification_params
    params.require(:notification).permit(:body, :resourceable_type, :notificationable_type, :created_at)
  end

end

app/controllers/support/offers_controller.rb
# frozen_string_literal: true

class Support::OffersController < ApplicationController
  def index
    offers = Offer.all.order(created_at: :desc).paginate(:page => params[:current_page], :per_page => 100)
    respond_to do |format|
      format.html {@offers = Offer.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 100)}
      format.csv do
        send_data offers.to_csv
        @csv = true
      end
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @offer_quotations = @offer.offer_quotations
    @offer_quotation = OfferQuotation.new
    @image = Image.new
  end

  def create_quotation
    offer_quotation = OfferQuotation.new(offer_quotation_params)  
    if offer_quotation.save! 
      offer_gall = params[:offer_quotation][:offer_quotation_gallery]
      offer_quotation.offer_quotation_galleries.create!(name:offer_gall[:name])
      offer_gall[:image][:image].each do |f|
        offer_quotation.offer_quotation_galleries.first.images.create!(image:f, description:"image")
      end
      offer_quotation.offer_measurements.create!(data:{"tags"=>params[:offer_quotation][:offer_measurement][:data].split(/,\s+/).map(&:capitalize)})
      redirect_to support_offer_path(offer_quotation.offer_id)
    else
      redirect_to root_url
    end
  end

  def update_quotation
    offer_quotation = OfferQuotation.find_by(offer_id:params[:offer_id]) rescue nil
    offer_gallery = OfferQuotationGallery.find(params[:offer_id]) rescue nil
    if params[:commit] == "Update Measurement"
      a = offer_quotation.offer_measurements.first
      a.data = JSON.parse params[:offer_measurement][:data].gsub('=>', ':')
      a.save!
      flash[:success] = "Offer Updated"
      redirect_to support_offer_path(params[:offer_id])
    elsif params[:commit] == "Name Update"
      offer_gallery.update(name:params[:offer_quotation_gallery][:name]) 
      flash[:success] = "Offer Updated"
      redirect_to request.referer     
    else
      offer_quotation.update(offer_quotation_params)
      flash[:success] = "Offer Updated"
      redirect_to support_offer_path(params[:offer_id])
    end
  end

  def gallery_images
    image = Image.new(gallery_image_params)
    if image.save!
      flash[:success] = "Image Uploaded"
      redirect_to request.referer
    else
      redirect_to support_offers_path
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to support_offers_path
    flash[:success] = "Offer Deleted"
  end

  private

  def offer_quotation_params
    params.require(:offer_quotation).permit(:price, :description, :request_id, :designer_note, :offer_id, offer_quotation_galleries_attributes: [:name ], images_attributes: %i[image description], offer_measurements_attributes: [data: {}]  )
  end

  def gallery_image_params
    params.require(:image).permit(:image, :imageable_id, :imageable_type, :description, :serial_number)
  end
end

app/controllers/support/orders_controller.rb
class Support::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "User", conversationable_id:@order.user).first 
  end

  def index
    orders = Order.order(created_at: :desc).all
    @order = Order.find(params[:format]) rescue nil
    if params[:commit] == 'Ship_To_QC'         # it checks if the user has clicked publish the it updates the form with publish
      @order.update(status:"shipped_to_qc")
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Delivered_To_QC'
      @order.update(status:"delivered_to_qc")
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == "In_QC"
      @order.update(status:"in_qc")
      NotificationsMailer.under_qc(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Ship_To_User'
      @order.update(status:"shipped_to_user")
      NotificationsMailer.shipped_to_user(@order).deliver_now
      NotificationsMailer.designer_shipped(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Deliver_To_User'
      @order.update(status:"delivered_to_user")
      NotificationsMailer.product_deliverd(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Reject'
      @order.update(status:"rejected_by_qc")
      NotificationsMailer.rejected_in_qc(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    end
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "User" )
    respond_to do |format|
      format.html {@orders = Order.order(created_at: :desc).all}
      format.csv do
        send_data orders.to_csv
        @csv = true
      end
    end
  end  

  private

  def search_params
    params.require(:search).permit(:query)[:query].split('(').last.tr(')', '')
  end
end

app/controllers/v1/supports/base_controller.rb
# frozen_string_literal: true

class V1::Supports::BaseController < ApiController
  include BaseHelpers
end

app/controllers/v1/supports/messages_controller.rb
class V1::Supports::MessagesController < V1::Supports::BaseController
	include Messageable
end

app/views/support/offers/index.html.erb
<h4 class="center">Offers</h4>
<br>
<%= will_paginate @offers %>
<br>
<%= link_to "Download Page", support_offers_path(format: "csv", current_page: @offers.current_page) %>
<br>
<div class="row">
  <table class="highlight"> 
    <thead>
      <tr>
        <th colspan="1" class="center">Designer Name</th>
        <th colspan="1" class="center">User Username</th>
        <th colspan="1" class="center">Request Name</th>
        <th colspan="1" class="center">SubCategory</th>
        <th colspan="1" class="center">No. of Quotations</th>
        <th colspan="1" class="center">Date</th>
        <th colspan="1" class="center">Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @offers.each do |offer| %>
        <tr id="js-data-row">  
          <td colspan="1" class="center">
            <%= link_to offer.designer.full_name, support_designer_path(offer.designer) %>
          </td>
          <td colspan="1" class="center">
            <%= link_to offer.request.user.username, support_user_path(offer.request.user) %>
          </td>
          <td colspan="1" class="center">
            <%= link_to offer.request.name.titleize, support_request_path(offer.request) %>
          </td>
          <td colspan="1" class="center">
            <%= offer.request.sub_category.name %>
          </td>
          <td colspan="1" class="center">
            <%= link_to offer.offer_quotations.count, support_offer_path(offer) %>
          </td> 
          <td colspan="1" class="center"><%= offer.created_at.strftime('%d %B %Y') %></td>
          <td colspan="1" class="center"><%= link_to "Delete", support_offer_path(offer), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= will_paginate @offers %>
<br>

app/views/support/offers/show.html.erb
<br><button class="waves-effect waves-light btn quotation_button">Click Here To Create a New Quotation</button><br>
<div class="card" id="quotation" style="display:none">
	<br>
	<h4 class="center">New Quotation</h4>
	<%= form_for @offer_quotation, :url => support_offer_quotation_path(@offer.id) do |f| %>
		<%= f.label :price %>
		<%= f.text_field :price, required:true %><br>
		<%= f.label :description %>
		<%= f.text_area :description, required:true, class: "materialize-textarea" %><br>
		<%= f.hidden_field :offer_id, value:@offer.id %>
		<%= f.fields_for :offer_quotation_gallery do |ff| %>
			<%= ff.label :gallery_name, required:true %>
			<%= ff.text_field :name, required:true  %><br>
			<%= ff.fields_for :image do |image| %>
				<%= image.file_field :image, multiple: true, required:true %><br>
			<% end %>
		<% end %>
		<br>
		<%= f.fields_for :offer_measurement do |ff| %>
			<%= f.label :Measurements_separate_with_comma %>
			<%= ff.text_field :data, required:true %>
		<% end %>
		<%= f.submit "Create", class: "waves-effect waves-light btn" %>
	<% end %>
	<br>
</div>

<% @offer_quotations.each_with_index do |offquo, index| %>
	<div class="row">
		<div class="col s12">
			<div class="card">
				<div class="card-content">
					<div class="row">
						<div class="col s12" style="text-align:center;"><h5><b>Quotation <%= index + 1 %></b></h5></div>
					</div>
					<%= form_for offquo, :url => support_offer_update_path(@offer) do |f| %>
						<p class="card-stats-title">Price:
							<b><%= f.text_field :price %></b>
						</p>
						<p class="card-stats-title">Description:
							<b><%= f.text_field :description %></b>
						</p>
						<p class="card-stats-title">Designer Note:
							<b><%= f.text_field :designer_note %></b>
						</p>
						<%= f.submit "Update Quotation" %>
					<% end %>
					<p class="card-stats-title">Offer Measurement:
				  	<% offquo.offer_measurements.each do |offmeas| %>
				  		<%= form_for offmeas, :url => support_offer_update_path(@offer)  do |f| %>
				  			<b><%= f.text_field :data %></b>
				  			<%= f.submit "Update Measurement" %>
				  		<% end %>
				  	<% end %>
					</p>
					<b><h5><u>Galleries:</u></h5></b>
					<% offquo.offer_quotation_galleries.each do |offgall| %>  	
				  	<p class="card-stats-title">
				  		<%= form_for offgall, :url => support_offer_update_path(offgall)  do |f| %>
				  			<%= f.text_field :name %>
				  			<%= f.submit "Name Update" %>
				  		<% end %>
				  		<br>		
				  	</p>
				  	<p class="card-stats-title">
				  		<% offgall.images.each do |gallery_image| %>            
				      	<a data-fancybox="gallery" href="<%= gallery_image.image_url %>"><img src="<%= gallery_image.image_url %>" id="thumb"></a>
				  		<% end %> 	
				  	</p>
				  	<%= form_for @image, :url => gallery_images_path, :html => {:method => :post} do |f| %>
						  <%= f.hidden_field :imageable_id, value:offgall.id %>
						  <%= f.hidden_field :imageable_type, value:"OfferQuotationGallery" %>
						  <%= f.hidden_field :description, value:"GalleryImage" %>
						  <%= f.hidden_field :serial_number, value:1 %>
						  <%= f.hidden_field :description, value:"image" %>
						  <%= f.file_field :image %>
						  <%= f.submit "Gallery" %>
						<% end %>
				  <% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

<script type="text/javascript">
	$(".quotation_button").click(function(){
    $("#quotation").toggle();
	});
</script>