config/routes.rb
# frozen_string_literal: true

Rails.application.routes.default_url_options = {
    host: ENV['APPLICATION_BASE_URL']
}

Rails.application.routes.draw do
  resources :config_variables
  

  resources :picks
  mount ActionCable.server => '/cable'

  devise_for :supports
  scope module: :support do
    get '/', to: 'home#index', as: :support_root
    authenticated :support do
      get '/search/users', to: 'search#users', as: :support_user_search
      get '/search/designers', to: 'search#designers', as: :support_designer_search
      get '/search/orders', to: 'search#orders', as: :support_order_search
      get '/search/requests', to: 'search#requests', as: :support_request_search
      get 'search/user-suggestions', to: 'search#users_suggestions'
      get 'search/designer-suggestions', to: 'search#designers_suggestions'
      
      # Generating Reports Based on the Queries 
      get 'supports/reports' => 'reports#list_reports', as: :support_reports 
      get 'supports/requests_24' => 'reports#requests_24'
      get 'supports/requests_48' => 'reports#requests_48'
      get 'supports/no_offer_custumise_24' => 'reports#no_offer_custumise_24'
      get 'supports/no_offer_custumise_48' => 'reports#no_offer_custumise_48'
      get 'supports/awating_meas' => 'reports#awating_meas'
      get 'supports/no_offer_requests_24' => 'reports#no_offer_requests_24'
      get 'supports/no_offer_requests_48' => 'reports#no_offer_requests_48'
      get 'supports/user_nooffer_24' => 'reports#user_nooffer_24'
      get 'supports/user_nooffer_48' => 'reports#user_nooffer_48'
      get 'supports/hot_users' => 'reports#hot_users'
      get 'supports/warm_users' => 'reports#warm_users'
      get 'supports/cold_users' => 'reports#cold_users'
      get 'supports/offer_requests' => 'reports#offer_requests'
      get 'supports/requests_nooffers_10000' => 'reports#requests_nooffers_10000'
      get 'supports/requests_nooffers_10_15' => 'reports#requests_nooffers_10_15'
      get 'supports/requests_nooffers_15000' => 'reports#requests_nooffers_15000'

      

      resources :users, only: %i[index show update], as: :support_users
      resources :designers, only: %i[index show], as: :support_designers
      resources :requests, only: %i[index show update create], as: :support_requests do
        patch :approve
        patch :reject
      end
      get '/send_messages' => 'messages#index'
      post '/send_messages' => 'messages#create'
      post 'supports/conversations' => 'users#create', as: :support_conversation
      resources :orders, only: %i[index], as: :support_orders  
      resources :orders, only: %i[show], as: :support_show_orders  
      resources :offers, only: %i[index show destroy], as: :support_offers  
      post 'offer_quotation/:offer_id' => 'offers#create_quotation', as: :support_offer_quotation
      patch 'offer_quotation/:offer_id' => 'offers#update_quotation', as: :support_offer_update 

      resources :chats, only: %[index], as: :support_chats
    end
  end

  scope module: :v1, path: 'supports', constraints: RouteConstraints.new(version: 1, default: true),
  defaults: { format: :json } do
    scope module: :supports do
      post 'login', to: 'sessions#create'
      post 'update_devise_token', to: 'registrations#update_devise_token'
      #notifications
      post 'notifications', to: 'messages#notifications'

      resources :conversations, only: %i[index create show destroy] do
        collection do
          post :chat_type
          post :fetch_conversation
          get :init_data
        end
        member do
          resources :messages, only: %i[index create update]
        end
      end
    end
  end

  get '/quoation/:id' => 'support/requests#show_request_quo', as: :quoation
  get '/product/:id' => 'support/designers#show_product_details', as: :product  

  get '/chat/:id' => 'support/requests#chat', as: :chat
  post '/chat/:id' => 'support/requests#chat_post', as: :chat_post
  post '/request_images' => 'support/requests#request_images'

  post '/gallery_images' => 'support/offers#gallery_images'

  get '/designers/measurements' => 'v1/designers/offer_quotations#measurement_tags'

  get '/push_token' => 'support/push_tokens#index'
  post '/push_token' => 'support/push_tokens#create', as: :push_create

  get '/users/create_request/:id' => 'support/users#create_request', as: :support_create_request  

  resources :measurement_tags
  
  resources :events, only: %i[index create]


  # constraints(subdomain: 'support') do
  #   devise_for :supports, path: ''
  #   scope module: :support do
  #     get '/', to: 'home#index', as: :support_root
  #     authenticated :support do
  #       get '/search/users', to: 'search#users', as: :support_user_search
  #       get '/search/designers', to: 'search#designers', as: :support_designer_search
  #       get '/search/orders', to: 'search#orders', as: :support_order_search
  #       get 'search/user-suggestions', to: 'search#users_suggestions'
  #       get 'search/designer-suggestions', to: 'search#designers_suggestions'
  #       resources :users, only: %i[index show], as: :support_users
  #       resources :designers, only: %i[index show], as: :support_designers
  #       resources :requests, only: %i[index show], as: :support_requests do
  #         patch :approve
  #         patch :reject
  #       end
  #       resources :orders, only: %i[index show], as: :support_orders
  #     end
  #   end
  # end

  root 'home#index'

  scope module: :v1, path: 'users', constraints: RouteConstraints.new(version: 1, default: true),
    defaults: { format: :json } do
    scope module: :users do
      # Registration
      post 'sign-up', to: 'registrations#create'
      get 'confirm/:token', to: 'registrations#confirm'
      post 'resend-confirmation-email', to: 'registrations#resend_confirmation'
      post 'send-reset-password-instructions', to: 'registrations#send_reset_password_instructions'
      get 'reset-password/:token', to: 'registrations#reset_password'
      get 'people', to: 'registrations#people'
      post 'update-password', to: 'registrations#update_password'
      post 'update-mobile-number', to: 'registrations#update_mobile_number'
      post 'update_devise_token', to: 'registrations#update_devise_token'
      post 'update_membership', to: 'registrations#update_membership'
      get 'resend-otp', to: 'registrations#resend_otp'
      post 'verify-otp', to: 'registrations#verify_otp'
      get 'me', to: 'registrations#show'
      post 'me/update', to: 'registrations#update'
      delete '/me/delete', to: 'registrations#destroy'

      #notifications
      post 'notifications', to: 'messages#notifications'
      # Authentication
      post 'login', to: 'sessions#create'
      match 'auth/facebook', to: 'sessions#facebook', via: %i[get post]
      match 'auth/google', to: 'sessions#google', via: %i[get post]

      # Home Controller
      get 'home/mobile', to: 'home#mobile'
      get 'home/mobile_v2', to: 'home#mobile_v2'

      # Sub Categories
      resources :sub_categories, only: :index, path: 'sub-categories'

      # Designers
      resources :designers, only: %i[index show]

      # Requests
      resources :requests, only: %i[index create show] do
        collection do
          get :init_data, path: 'init-data'
          get 'designers/:category_id' => :designers
          post  :create_v2
          post  :create_request_images_v2
        end
        member do
          resources :offers, only: %i[index show]
        end
      end

      # Offers
      resources :offers, only: %i[index show]

      # Shipping Addresses
      resources :addresses, only: %i[index create]

      resources :products, only: %i[index show]

      get 'explore/mobile', to: 'explore#mobile'
      get 'explore/mobile_v2', to: 'explore#mobile_v2'
      get 'search/:q', to: 'search#index'
      post 'external-search/create', to: 'external_searches#create'
      get 'external-search/modal-suggestions', to: 'external_searches#search_suggestions'
      get 'external-search/top-suggestions', to: 'external_searches#top_query_suggestions'

      resources :orders, only: %i[index show create] do
        member do
          get :pay
          get :measurement_tags
          post :update_measurements
          post :update_measurements_v2
          post :submit_options
          get :cancel_order
        end
      end

      resources :order_payments, only: %i[create update]

      # resources :support_chats, only: %i[create index] do
      #   member do
      #     resources :conversations, only: %i[create]
      #   end
      # end

      resources :conversations, only: %i[index create show destroy] do
        collection do
          get :chat_type
          post :fetch_conversation
          #get :chat_type_request
        end
        member do
          resources :messages, only: %i[index create update]
        end
      end

      resources :offer_quotation_chats, only: %i[create] do
        member do
          resources :conversations, only: %i[create]
        end
      end

      resources :user_favorite_products, only: :create, path: 'add-to-wishlist'
      resources :user_favorite_designers, only: :create, path: 'add-to-favorites'
    end
  end

  scope module: :v1, path: 'designers', constraints: RouteConstraints.new(version: 1, default: true),
    defaults: { format: :json } do
    scope module: :designers do
      # Registration
      post 'sign-up', to: 'registrations#create'
      get 'confirm/:token', to: 'registrations#confirm'
      post 'resend-confirmation-email', to: 'registrations#resend_confirmation'
      post 'send-reset-password-instructions', to: 'registrations#send_reset_password_instructions'
      get 'reset-password/:token', to: 'registrations#reset_password', :constraints => { :token => /.+@.+\..*/ }
      post 'update-password', to: 'registrations#update_password'
      post 'update-mobile-number', to: 'registrations#update_mobile_number'

app/controllers/support/chats_controller.rb
class Support::ChatsController < ApplicationController
  
  def index
    convo_id = Message.pluck(:conversation_id).uniq
    user_id = Conversation.where(id:convo_id).pluck(:conversationable_id)
    @users = User.where(id:user_id).order(updated_at: :desc).paginate(:page => params[:page], :per_page => 100)
  end

end

app/controllers/support/designers_controller.rb
# frozen_string_literal: true

class Support::DesignersController < ApplicationController
  def index
    @designers = Designer.order(full_name: :asc).all
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "Designer" )
    @conversation = Conversation.new
  end

  def show
    @designer = Designer.find(params[:id])
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "Designer", conversationable_id:@designer).first 
  end

  def show_product_details
  	@product = Product.find(params[:id])
  end
end

app/controllers/support/home_controller.rb
# frozen_string_literal: true

class Support::HomeController < ApplicationController
  def index
    if support_signed_in?
      @data = {
        total_users:     User.count,
        total_designers: Designer.count,
        total_requests:  Request.count,
        total_offers:    OfferQuotation.count,
        total_orders:    Order.count,
        total_products:  Product.count
      }
    else
      redirect_to '/supports/sign_in'
    end
  end
end

app/controllers/support/messages_controller.rb
# frozen_string_literal: true
class Support::MessagesController < ApplicationController
    
  def index
    @notification = Notification.new
  end

  def create
    @notification = Notification.new(notification_params)
    if @notification.save!(validate:false)
      if params[:commit] == "CLOSE REQUEST"
        @notification.delay.close_request_message(@notification) 
      elsif params[:commit] == "SUBMIT REQUEST"
        @notification.delay.submit_request_message(@notification)
      elsif params[:commit] == "ALL USERS"    
        @notification.delay.all_users_message
      end
      flash[:success] == "Message Sent"
      redirect_to send_messages_path
    else
      redirect_to root_url
    end  
  end

  private

  def notification_params
    params.require(:notification).permit(:body, :resourceable_type, :notificationable_type, :created_at)
  end

end

app/controllers/support/offers_controller.rb
# frozen_string_literal: true

class Support::OffersController < ApplicationController
  def index
    offers = Offer.all.order(created_at: :desc).paginate(:page => params[:current_page], :per_page => 100)
    respond_to do |format|
      format.html {@offers = Offer.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 100)}
      format.csv do
        send_data offers.to_csv
        @csv = true
      end
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @offer_quotations = @offer.offer_quotations
    @offer_quotation = OfferQuotation.new
    @image = Image.new
  end

  def create_quotation
    offer_quotation = OfferQuotation.new(offer_quotation_params)  
    if offer_quotation.save! 
      offer_gall = params[:offer_quotation][:offer_quotation_gallery]
      offer_quotation.offer_quotation_galleries.create!(name:offer_gall[:name])
      offer_gall[:image][:image].each do |f|
        offer_quotation.offer_quotation_galleries.first.images.create!(image:f, description:"image")
      end
      offer_quotation.offer_measurements.create!(data:{"tags"=>params[:offer_quotation][:offer_measurement][:data].split(/,\s+/).map(&:capitalize)})
      redirect_to support_offer_path(offer_quotation.offer_id)
    else
      redirect_to root_url
    end
  end

  def update_quotation
    offer_quotation = OfferQuotation.find_by(offer_id:params[:offer_id]) rescue nil
    offer_gallery = OfferQuotationGallery.find(params[:offer_id]) rescue nil
    if params[:commit] == "Update Measurement"
      a = offer_quotation.offer_measurements.first
      a.data = JSON.parse params[:offer_measurement][:data].gsub('=>', ':')
      a.save!
      flash[:success] = "Offer Updated"
      redirect_to support_offer_path(params[:offer_id])
    elsif params[:commit] == "Name Update"
      offer_gallery.update(name:params[:offer_quotation_gallery][:name]) 
      flash[:success] = "Offer Updated"
      redirect_to request.referer     
    else
      offer_quotation.update(offer_quotation_params)
      flash[:success] = "Offer Updated"
      redirect_to support_offer_path(params[:offer_id])
    end
  end

  def gallery_images
    image = Image.new(gallery_image_params)
    if image.save!
      flash[:success] = "Image Uploaded"
      redirect_to request.referer
    else
      redirect_to support_offers_path
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to support_offers_path
    flash[:success] = "Offer Deleted"
  end

  private

  def offer_quotation_params
    params.require(:offer_quotation).permit(:price, :description, :request_id, :designer_note, :offer_id, offer_quotation_galleries_attributes: [:name ], images_attributes: %i[image description], offer_measurements_attributes: [data: {}]  )
  end

  def gallery_image_params
    params.require(:image).permit(:image, :imageable_id, :imageable_type, :description, :serial_number)
  end
end

app/controllers/support/orders_controller.rb
class Support::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "User", conversationable_id:@order.user).first 
  end

  def index
    orders = Order.order(created_at: :desc).all
    @order = Order.find(params[:format]) rescue nil
    if params[:commit] == 'Ship_To_QC'         # it checks if the user has clicked publish the it updates the form with publish
      @order.update(status:"shipped_to_qc")
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Delivered_To_QC'
      @order.update(status:"delivered_to_qc")
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == "In_QC"
      @order.update(status:"in_qc")
      NotificationsMailer.under_qc(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Ship_To_User'
      @order.update(status:"shipped_to_user")
      NotificationsMailer.shipped_to_user(@order).deliver_now
      NotificationsMailer.designer_shipped(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Deliver_To_User'
      @order.update(status:"delivered_to_user")
      NotificationsMailer.product_deliverd(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    elsif params[:commit] == 'Reject'
      @order.update(status:"rejected_by_qc")
      NotificationsMailer.rejected_in_qc(@order).deliver_now
      flash[:success] = "Order Updated"
      redirect_to request.referer
    end
    @conversation = Conversation.new
    @convo =  Conversation.where(receiver_type:"support", conversationable_type: "User" )
    respond_to do |format|
      format.html {@orders = Order.order(created_at: :desc).all}
      format.csv do
        send_data orders.to_csv
        @csv = true
      end
    end
  end  

  private

  def search_params
    params.require(:search).permit(:query)[:query].split('(').last.tr(')', '')
  end
end

app/controllers/v1/supports/base_controller.rb
# frozen_string_literal: true

class V1::Supports::BaseController < ApiController
  include BaseHelpers
end

app/controllers/v1/supports/messages_controller.rb
class V1::Supports::MessagesController < V1::Supports::BaseController
	include Messageable
end

app/views/support/users/_table.html.erb
<!-- <div class="row">
  <div class="col s12">
    <div class="input-field">
      <input id="js-user-name-fuzzy" type="text" class="validate" placeholder="Enter the details of the user" autofocus>
    </div>
  </div>
</div> -->

<%= will_paginate users %>
<br>
<%= link_to "Download Page", support_users_path(format: "csv", current_page: @users.current_page ) %>
<br>

<div class="row">
  <table class="highlight">
    <thead>
      <tr>
        <th colspan="1" class="center">Full Name</th>
        <th colspan="1" class="center">Username</th>
        <% if current_support.role == "admin" %>
          <th colspan="1" class="center">Mobile Number</th>
          <th colspan="1" class="center">Email</th>
        <% end %>
        <th colspan="1" class="center">Gender</th>
        <th colspan="1" class="center">Requests made</th>
        <th colspan="1" class="center">Orders made</th>
        <th colspan="2" class="right">Behaviour</th>
        <th colspan="1" class="center">Update</th>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr id="js-data-row">
          <td colspan="1" class="center"><%= link_to user.full_name.titleize, support_user_path(user) %></td>

          <td colspan="1" class="center">
            <%= user.username %>
          </td>
          <% if current_support.role == "admin" %>
            <td colspan="1" class="center"><%= user.mobile_number %></td>

            <td colspan="1" class="center">
              <%= user.email %>
            </td>
          <% end %>

          <td colspan="1" class="center">
            <%= user.gender %>
          </td>

          <td colspan="1" class="center">
            <%= user.requests.size %>
          </td>

          <td colspan="1" class="center">
            <%= user.orders.size %>
          </td>
          <td colspan="2" class="right">
            <%= form_for user, :url => support_user_path(user), remote: true do |f| %>
            <%= f.check_box :hot, id:"hot", class: "product-list"%><label for="hot" style="color:green">Hot?</label><br>
            <%= f.check_box :cold, id:"cold", class: "product-list" %><label for="cold" style="color:red">Cold?</label><br>
            <%= f.check_box :warm, id:"warm", class: "product-list"  %><label for="warm" style="color:#eaa508">Warm?</label>
          </td>
          <td colspan="1" class="center">
              <%= f.submit %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate users %>

<style type="text/css">
  
  #hot:checked + label:before{
  border-right: 2px solid green; /* You need to change the colour here */
  border-bottom: 2px solid green; /* And here */
  }
  #cold:checked + label:before{
  border-right: 2px solid red; /* You need to change the colour here */
  border-bottom: 2px solid red; /* And here */
  }
  
</style>

app/views/support/users/index.html.erb
<div class="row">
  <h3 class="center">Users</h3>
</div>

<div class="row">
  <% if @users.present? %>
   	<%= render 'table', users: @users %>
  <% else %>
    <h4>No users present in the database</h4>
  <% end %>
</div>

app/views/support/users/show.html.erb
<div class="vertical-spacer-5"></div>
<!-- Profile -->
<div class="row">
  <div class="col s12 m6 l6">
    <div class="card">
      <div class="card-content">
        <h5 class="card-stats-number center">Profile</h5>
        <p class="card-stats-title">Name:
          <b><%= @user.full_name %></b>
        </p>
        <% if current_support.role == "admin" %>
          <p class="card-stats-title">Email:
            <b><%= @user.email %></b>
          </p>
          <p class="card-stats-title">Mobile:
            <b><%= @user.mobile_number %></b>
          </p>
        <% end %>
        <p class="card-stats-title">Username:
          <b><%= @user.username %></b>
        </p>
        <p class="card-stats-title">Confirmed Email?:
          <b><%= t @user.confirmed? %></b>
        </p>
        <p class="card-stats-title">Verified Number?:
          <b><%= t @user.verified? %></b>
        </p>
        <p class="card-stats-title">Bio:
          <b><%= @user.bio ? @user.bio : 'No bio' %></b>
        </p>
        <p class="card-stats-title fixed">

          <%= form_for @user, :url => support_user_path(@user) do |f| %>
            <p class="card-stats-title"><b>Support Notes:</b>
              <%= f.text_area :support_notes , class: "materialize-textarea" %>
            </p>
            User Behaviour:<br>
            <%= f.check_box :hot, id:"hot", class: "product-list"%><label for="hot" style="color:green">Hot?</label><br>
            <%= f.check_box :cold, id:"cold", class: "product-list" %><label for="cold" style="color:red">Cold?</label><br>
            <%= f.check_box :warm, id:"warm", class: "product-list"  %><label for="warm" style="color:#eaa508">Warm?</label><br><br>
            <%= f.submit %>
          <% end %>
          
        </p>
      </div>
    </div>
  </div>

  <!-- Orders and Requests -->
  <div class="col s12 m6 l6">
    <ul class="collapsible" data-collapsible="expandable">
      <li>
        <div class="collapsible-header">
          <a href="#">Orders</a>
        </div>

        <div class="collapsible-body">
          <ul class="collection">
            <li class="collection-item">
              <%= "Unpaid (#{@user.orders.where(status: :started).size})" %>
            </li>
            <li class="collection-item">
              <%= "Paid (#{@user.orders.where(status: :paid).size})" %>
            </li>
            <li class="collection-item">
              <%= "Designer Confirmed (#{@user.orders.where(status: :designer_confirmed).size})" %>
            </li>
            <li class="collection-item">
              <%= "User Awaiting More Options (#{@user.orders.where(status: :user_awaiting_more_options).size})" %>
            </li>
            <li class="collection-item">
              <%= "Designer Gave More Options (#{@user.orders.where(status: :designer_gave_more_options).size})" %>
            </li>
            <li class="collection-item">
              <%= "Designer Selected Fabric Unavailable (#{@user.orders.where(status: :designer_selected_fabric_unavailable).size})" %>
            </li>
            <li class="collection-item">
              <%= "Measurements Given (#{@user.orders.where(status: :measurements_given).size})" %>
            </li>
            <li class="collection-item">
              <%= "In Production (#{@user.orders.where(status: :in_production).size})" %>
            </li>
            <li class="collection-item">
              <%= "Shipped to QC (#{@user.orders.where(status: :shipped_to_qc).size})" %>
            </li>
            <li class="collection-item">
              <%= "Delivered to QC (#{@user.orders.where(status: :delivered_to_qc).size})" %>
            </li>
            <li class="collection-item">
              <%= "In QC (#{@user.orders.where(status: :in_qc).size})" %>
            </li>
            <li class="collection-item">
              <%= "Shipped to User (#{@user.orders.where(status: :shipped_to_user).size})" %>
            </li>
            <li class="collection-item">
              <%= "Delivered to User (#{@user.orders.where(status: :delivered_to_user).size})" %>
            </li>
            <li class="collection-item">
              <%= "Cancelled by User (#{@user.orders.where(status: :delivered_to_user).size})" %>
            </li>
          </ul>
        </div>
      </li>

      <li>
        <div class="collapsible-header active">
          <a href="#">Requests</a>
        </div>
        <div class="collapsible-body">
          <ul class="collection">
            <li class="collection-item">
              <%= "Active (#{@user.requests.where(status: :active).size})" %>
            </li>
            <li class="collection-item">
              <%= "Pending (#{@user.requests.where(status: :pending).size})" %>
            </li>
            <li class="collection-item">
              <%= "Unapproved (#{@user.requests.where(status: :unapproved).size})" %>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <span class="card-title" style="text-align:center">
          CHAT : 
          <% if @convo.present? %>
            <%= link_to image_tag("chat.png", width:"30x30"),
            chat_path(@convo.id), :target => "_blank"%>
          <% else %>
            <%= form_for @conversation, :url => support_conversation_path, :html => {:method => :post} do |f| %>
              <%= f.hidden_field :receiver_id , value:current_support.common_id %>
              <%= f.hidden_field :receiver_type , value:"support" %>
              <%= f.hidden_field :conversationable_id , value:@user.id %>
              <%= f.hidden_field :conversationable_type , value:"User" %>
              <%= f.submit "Initiate Chat" , class:"waves-effect waves-light btn" %>
            <% end %>
          <% end %>
        </span>
      </div>
    </div>
  </div>
  <div class="col s12 m6">
    <div class="card">
      <br>
      <div class="center">
        <%= link_to "Create Request For This User", support_create_request_path(@user), class:"waves-effect waves-light btn"  %>
      </div>  
      <br>
    </div>
  </div>

</div>


<!-- Requests List -->
<% if @user.requests.present? %>
  <div class="row">
    <h5 class="center">Requests</h5>
    <div class="col s12">
      <table class="highlight">
        <thead>
          <tr>
            <th colspan="4" class="center">Name</th>
            <th colspan="1" class="center">Status</th>
            <th colspan="1" class="center">Size</th>
            <th colspan="1" class="center">Timeline for User</th>
            <th colspan="1" class="center">Timeline for Designer</th>
            <th colspan="1" class="center">Sub Category</th>
            <th colspan="1" class="center">Address</th>
            <th colspan="1" class="center">Number of Designers</th>
            <th colspan="1" class="center">Number of Offers</th>
          </tr>
        </thead>
        <tbody>
          <% @user.as_request_json.sort {|x,y| y[:unread_message_count]<=>x[:unread_message_count]}.each do |request| %>
            <tr>
              <td colspan="4" class="center"><%= link_to request[:name], support_request_path(request) %></td>

              <td colspan="1" class="center"><%= request[:status].humanize %></td>

              <td colspan="1" class="center"><%= request[:size].upcase %></td>

              <td colspan="1" class="center"><%= "#{request[:timeline]} weeks" %></td>

              <td colspan="1" class="center"><%= "#{request[:timeline] - 2} weeks" %></td>

              <td colspan="1" class="center">
                <%= SubCategory.find(request[:sub_category_id]).name %>
              </td>

              <td colspan="1" class="center">
                <%= Address.find(request[:address_id]).formatted_address %>
              </td>

              <td colspan="1" class="center">
                <%= RequestDesigner.where(request_id:request[:id]).size %>
              </td>

              <td colspan="1" class="center">
                <%= Offer.where(request_id:request[:id]).size %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    
  </div>
<% else %>
  <h5>No Requests</h5>
<% end %>




<!-- Orders List -->
<% if @user.orders.present? %>
  <div class="row">
    <h5 class="center">Orders</h5>

    <div class="col s12">
      <table class="highlight">
      <thead>
        <tr>
          <th colspan="4" class="center">Name</th>
          <th colspan="1" class="center">Order ID</th>
          <th colspan="1" class="center">Status</th>
          <th colspan="1" class="center">Designer</th>
          <th colspan="1" class="center">Price</th>
          <th colspan="1" class="center">Ordered On</th>
          <th colspan="1" class="center">Shipping Address</th>
      </thead>
      <tbody>
        <% @user.as_order_json.sort {|x,y| y[:unread_message_count]<=>x[:unread_message_count]}.each do |order| %>
          <% ord = Order.find(order[:id]) %>
          <tr>
            <td colspan="4" class="center"><%= link_to Order.find(order[:id]).offer_quotation.offer.request.name, support_show_order_path(order) %></td> 

            <td colspan="1" class="center"><%= order[:order_id] %></td>

            <td colspan="1" class="center"><%= order[:status].humanize %></td>

            <td colspan="1" class="center"><%= ord.designer.designer_store_info.display_name %></td>

            <td colspan="1" class="center"><%= ord.offer_quotation.price %></td>

            <td colspan="1" class="center"><%= order[:created_at].strftime('%d %B %Y') %></td>

            <td colspan="1" class="center">
              <%= ord.offer_quotation.offer.request.address.formatted_address %>
            </td>
          </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
<% else %>
  <h5>No Orders</h5>
<% end %>


<style type="text/css">
  td.center
  {
    height: 140px;
  }
  #hot:checked + label:before{
  border-right: 2px solid green; /* You need to change the colour here */
  border-bottom: 2px solid green; /* And here */
  }
  #cold:checked + label:before{
  border-right: 2px solid red; /* You need to change the colour here */
  border-bottom: 2px solid red; /* And here */
  }
  
</style>

<script type="text/javascript">
   //Near checkboxes
  $('.product-list').click(function() {
      $(this).siblings('input:checkbox').prop('checked', false);
  });

</script>